// <auto-generated />
namespace Lab2.DataAccess.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EFContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EFContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031420386_EFContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
